[build-system]
requires = [
    "maturin>=0.14,<0.15"
]
build-backend = "maturin"

[project]
name = "rust_python_project_template"
authors = [
    {name = "Anthony Corletti", email = "rust_python_project_template@example.com"}
]
dynamic = [
    'description',
    'license',
    'readme',
    'version',
]
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
test = [
    "pytest >=6.2.5",
    "coverage >=6.1.1",
    "pytest-cov >=3.0.0",
]
dev = [
    "mypy >=0.910",
    "black >=21.10b0",
    "isort >=5.9.3",
    "ruff >=0.0.98",
    "pre-commit >=2.17.0",
]

[project.urls]
Documentation = "https://github.com/anthonycorletti/rust_python_project_template"

[tool.maturin]
bindings = 'pyo3'
sdist-include = ['Cargo.lock']

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 88
ignore = [
    "D10",
    "D415",
]
target-version = "py310"
extend-select = ["D"]
extend-ignore = [
    "D203",
    "D204",
    "D213",
    "D215",
    "D400",
    "D404",
    "D406",
    "D407",
    "D408",
    "D409",
    "D413",
]
